/**
 * 앱 상수 정의
 */

// 네비게이션 상수
export const SCREEN_NAMES: Record<string, string> = {
  ONBOARDING: 'Onboarding',
  SIGNUP: 'SignUp',
  LOGIN: 'Login',
  NICKNAME: 'Nickname',
  HOME: 'Home',
  DIARY: 'Diary',
  MISSION: 'Mission',
  CUSTOM_MISSION_CREATE: 'CustomMissionCreate',
  COUNSELING_SELECT: 'CounselingSelect',
  PLACES_SEARCH: 'PlacesSearch',
  SETTINGS: 'Settings',
  INFO: 'Info',
  COMMUNITY: 'Community',
  COMMUNITY_POST_CREATE: 'CommunityPostCreate',
  COMMUNITY_POST_EDIT: 'CommunityPostEdit',
  COMMUNITY_POST_DETAIL: 'CommunityPostDetail',
  MY_PAGE: 'MyPage',
  CALENDAR: 'Calendar',
  STATISTICS: 'Statistics',
  ADMIN_DASHBOARD: 'AdminDashboard',
  ADMIN_USER_LIST: 'AdminUserList',
  ADMIN_USER_DETAIL: 'AdminUserDetail',
  ADMIN_USER_EDIT: 'AdminUserEdit',
  MISSION_GROUP: 'MissionGroup',
  NOTIFICATION: 'Notification',
  MISSION_DETAIL: 'MissionDetail',
  BADGE_DETAIL: 'BadgeDetail',
  VERIFICATION_POST_CREATE: 'VerificationPostCreate',
  VERIFICATION_POST_DETAIL: 'VerificationPostDetail',
  FIND_ID: 'FindId',
  FIND_ID_RESULT: 'FindIdResult',
  FIND_PASSWORD: 'FindPassword',
  CHANGE_PASSWORD: 'ChangePassword',
  SOUND_SETTINGS: 'SoundSettings',
  MISSION_SET_LIST: 'MissionSetList',
  MISSION_SET_CREATE: 'MissionSetCreate',
  MISSION_SET_DETAIL: 'MissionSetDetail',
  MY_MISSION_SETS: 'MyMissionSets',
  MY_PROGRESS_DETAIL: 'MyProgressDetail',
  TODO_LIST: 'TodoList',
  TODO_LIST_CREATE: 'TodoListCreate',
  TODO_LIST_DETAIL: 'TodoListDetail',
  OAUTH_COMPLETE_SIGNUP: 'OAuthCompleteSignUp',
  SPONTANEOUS_MISSION_SETUP: 'SpontaneousMissionSetup',
  WAKE_UP_VERIFICATION: 'WakeUpVerification',
  REANT_CHAT: 'ReantChat',
} as const;
